### PR TITLE
Update sariah

### PR DESCRIPTION
**Pull request by sariah9**
added images, updated new main layout for homepage

### CODE REVIEW

**Comment by kenkoolio** [comment]
Looks good, just a few last things:

1. In recipes.js -> when you render oneRecipe, you are missing a forward-slash for the img path
"img: "images/recipeHeaders/" + rows[0].recipe_img," <--- missing a " / " before "images"


2. can you add more whitespace around the individual recipe, so that its not spread out to the edges of the page

3. what is the purpose of "individualMain.handlebars"?

**Comment by sariah9** [comment]
1. I added the slash (/) before images in both recipes and recipe_id. Thanks for letting me know. 
2. Added padding of 4%. Let me know if you think that's too much.
3. Deleted individualMain and also all the images and files that were no longer needed by me... possibly need to delete Kevin's recipe1, 2, 3?

**Comment by kenkoolio** [comment]
Looks good. Merged

**Review by kenkoolio — APPROVED** [review]
good to go

**Pull request merged**
